version: '3.8'

services:

  web:
    build: ./project
    ports:
      - 8004:8000
    command: poetry run uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./project
    command: poetry run celery -A worker.celery worker
    volumes:
      - ./project:/usr/src/app
      - /Users/bmiller/Runestone/books:/books
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
