version: '3.8'

services:

  web:
    build: ./authorserver
    ports:
      - 8004:8000
    command: ./start-web.sh
    volumes:
      - ./authorserver:/usr/src/app
      - /Users/bmiller/Runestone/books:/books
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEV_DBURL=${DEV_DBURL}
    depends_on:
      - redis

  worker:
    build: ./authorserver
    command: ./start-worker.sh
    volumes:
      - ./authorserver:/usr/src/app
      - /Users/bmiller/Runestone/books:/books
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEV_DBURL=${DEV_DBURL}
      - WEB2PY_CONFIG=${SERVER_CONFIG}
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
